### ISSUE TITLE
Wide&Deep 和 Wide&DeepPreHash 特征不一致？

### ISSUE THREAD

**Issue by Yazhou-Liu** [THUIR/PreHash#1]
看了下论文里的代码，作者在测试Wide&Deep 和 Wide&DeepPreHash的时候，Wide&Deep好像没有加 itemID和userID的特征，想问下，对比测试的时候也是这样嘛

**Comment by Shuriken13** [comment]
Wide&Deep加了ID特征，都放到feed_dict[X]里了。

**Comment by Shuriken13** [comment]
Wide&Deep的feed_dict[X]里有ID， Wide&DeepPreHash的feed_dict[X]里没有ID
