### ISSUE TITLE
关于anchor user选择的问题

### ISSUE THREAD

**Issue by DoubleYing** [THUIR/PreHash#4]
在PrehashDP.py中提到了4种选择anchor user的方式。分别是1.随机选择；2.选择点击最多的用户；3.kmeans；4.jaccard
1，2两种方式，都只得到了k个anchor user
3，4是将用户分到k个cluster中，这是不是认为每个user都是anchor user了？
那么在经过prehash分桶后，每个用户就固定只得到1个桶的向量作为它的hash user vector了吗？

**Comment by Shuriken13** [comment]
这是做对比实验的，kmeans和jaccard对应论文Ablation Study，是为了证明简单用这些聚类方法把用户聚类效果不够好。方便实现写在这里了，并不是为了提供anchor user的选取方式。

**Comment by DoubleYing** [comment]
好的，了解了。那关于这个锚点用户的选择有点难评价其好坏。在我们的场景里，选择点击最多的用户作为锚点用户得到的召回效果并不理想。所以想请教一下，关于锚点用户的选择还有什么其他的方式吗？

**Comment by Shuriken13** [comment]
个人觉得对于比较手动的方式可以根据具体数据划分不同年龄段、不同职业等类型的用户，然后每种类型选一些活跃用户出来，尽量覆盖各种类型的偏好。比较自动的方式就是预先对用户根据历史做聚类，然后从每个类别中选出一些活跃用户。

**Comment by tearscoco** [comment]
请问anchor user的数量有分析过吗？对于用户数量特别大的场景，可能anchor数量需要上万，这样的情况下prehash分桶以及顶层的topK采样能有比较好的结果吗？

**Comment by Shuriken13** [comment]
论文里有分析，但是我们实验只做到千级别就没有什么提升了，万级别没有尝试过。

**Comment by tearscoco** [comment]
了解~不过对于完全没有历史行为的用户，在没有profile信息encode情况下，也没有办法生成preHash的表征？

**Comment by Shuriken13** [comment]
我觉得完全没有个性化信息的话可能也没法做这种有用户画像的个性化推荐。可以考虑session-based方法。

**Comment by sherlock1987** [comment]
想继续问一下，锚点用户如何更新呢？虽然在您的论文里面是固定的，但是我比较好奇的是如何动态的更新锚点用户。如果可以的话，请问有什么手段呢？

**Comment by Shuriken13** [comment]
可能可以同时优化一个用户取某个单独向量或取一堆向量的加权和，然后二者取一。但我其实现在觉得动态选择锚用户的意义不大。更好的一个改进思路是就把每个桶理解为一种特定类型偏好，用disentangle方式去保证偏好多样性，然后每个用户由多个偏好向量构成表示，由哪些偏好向量可以使用类似结构并结合bandit搜索或者gumbel采样直接优化。
